- name: play1
  hosts: dev
  tasks:
   - name: print heloo from task1 and play 1
     ansible.builtin.debug:
          msg: hai from task1 and play1

   - name: print heloo from task2 and play1  
     ansible.builtin.debug:
          msg: hai from task2 play1    

- name: play2
  hosts: dev
  tasks:
   - name: print heloo from task2 and play2
     ansible.builtin.debug:
          msg: hai from task2 and play2

- name: play3
  hosts: dev
  tasks:
    - name: print heloo from task3 and play3
      ansible.builtin.debug:
          msg: hai from task3 and play3