- name: play1
  hosts: all
  tasks:
  - name: print hello from task1 and play1
    ansible.builtin.debug:
        msg: hai task from play1

  - name: print hello from task1 and play1
    ansible.builtin.debug:
        msg: hai task from play1


