# - name: play1
#   hosts: all
#   tasks:
#    - name: print heloo from task1 and play 1
#      ansible.buitlin.debug:
#           msg: hai from task1 and play1

#    - name: print heloo from task2 and play1  
#      ansible.builtin.debug:
#           msg: hai from task2 play1    
