- name: demo using varibales
  hosts: all
  vars: 
    URL: play.google.com
  tasks:
    - name: printing url 
      ansible.builtin.debug:
        msg: value of url is {{URL}}

    - name: printing url 
      ansible.builtin.debug:
        msg: value of space url is {{ URL }}

    - name: printing url 
      ansible.builtin.debug:
        msg: "{{ URL }}"
    - vars:    
       URL: task.google.com
        