- name: play1
  hosts: dev
  vars: 
    URL: cerulean.com
    CLI: cli.com
  vars_files:
    - demo-url.yaml
  tasks:
   - name: printing value of play 1
     ansible.builtin.debug:
       msg: website url is {{URL}}

   - name: printing value of play 2
     ansible.builtin.debug:
        msg: value of url is {{CLI}}
     vars:
        URL: flipkart.com


