- name: play1
  hosts: dev
  vars: 
    URL: cerulean.com
  tasks:
   - name: printing value of play 1
     ansible.builtin.debug:
       msg: website url is {{URL}}

- name: play2
  hosts: all
  tasks:
   - name: printing value of play 2
     ansible.builtin.debug:
        msg: value of url is {{URL}}
    #  vars: 
    #   URL: flipkart.com
