- name: checking when condition
  hosts: all
  vars:
    # ACTION: true
      foo: value
  tasks:
    - name: printing centos 
      ansible.builtin.debug:
         msg: hello from centos
      when: ACTION is undefined    

    - name: Run the command if "foo" is defined
      ansible.builtin.shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - name: Fail if "bar" is undefined
      ansible.builtin.debug: msg="Bailing out. This play requires 'bar'"
      when: bar is undefined