- name: checking when condition
  hosts: all
  vars:
    ACTION: true
    bar: akash
    foo: vinod
  tasks:
    - name: printing centos 
      ansible.builtin.debug:
         msg: hello from centos
      when: ACTION     

    - name: Run the command if "foo" is defined
      ansible.builtin.shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      register: out
      when: foo is defined

    - name: read the output
      ansible.builtin.debug:
          msg: "{{OUT}}"      

    - name: Fail if "bar" is undefined
      ansible.builtin.fail: msg="Bailing out. This play requires 'bar'"
      when: bar is undefined