- name: demo using sudo or root user
  hosts: all
  become: yes
  tasks:
    - name: running shell command
      ansible.builtin.shell: id
      register: OUT

    - name: read the output
      ansible.builtin.debug:
          msg: "{{OUT.stdout}}"

    - name: running shell command
      ansible.builtin.shell: id
      register: OUT
      become_user: centos

    - name: read the output
      ansible.builtin.debug:
          msg: "{{OUT.stdout}}"
