- name: var demo
  hosts: all
  vars:
    URL: play.google.com
    CLI_URL: cli.global.com
  vars_files:
    - demo-url.yaml  
  tasks:
    - name: var demo task1
      ansible.builtin.debug:
         msg: website url is {{ URL }} 

    - name: var demo task2
      ansible.builtin.debug:
         msg: "{{ URL }}"
      vars:
        URL: play.locals.com     

    - name: var demo task3
      ansible.builtin.debug:
         msg: "{{ CLI_URL }}"

